[package]
name = "bevy-scene-hook"
authors = ["Nicola Papale"]
description = "Ad-hoc component insertion for bevy scenes"
license = "Apache-2.0"
readme = "Readme.md"
keywords = ["bevy"]
categories = ["game-development"]
repository = "https://github.com/nicopap/bevy-scene-hook"
version = "3.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8.0-dev", default-features = false }

[patch.crates-io]
bevy = { git = "https://github.com/mockersf/bevy", branch = "scene-bundle" }
